services:
  web:
    build: .
    container_name: appsec-login-daemon
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      # - ./data:/app/data # production
    environment:
      - PYTHONUNBUFFERED=1
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - INIT_DB=True # destructive: re-initializes the database on each container start
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped
