services:
  web:
    build: .
    container_name: appsec-login-daemon
    ports:
      - "8000:8000"
    volumes:
      - ./src:/workspace
      - ./data:/data
    environment:
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - INIT_DATA=${INIT_DATA}
    restart: unless-stopped
