services:
  web:
    build: .
    container_name: flask
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      # - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - SECRET_KEY= "c08c0daf2d56cec64970aff25efd527ec7559747b9eb6cec713c890d7f2bea46"
      - INIT_DB=True # destructive: re-initializes the database on each container start
    restart: unless-stopped
